package org.maxwe.android.project.sample.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import org.maxwe.android.project.sample.dao.CustomerEntity;

import org.maxwe.android.project.sample.dao.CustomerEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customerEntityDaoConfig;

    private final CustomerEntityDao customerEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customerEntityDaoConfig = daoConfigMap.get(CustomerEntityDao.class).clone();
        customerEntityDaoConfig.initIdentityScope(type);

        customerEntityDao = new CustomerEntityDao(customerEntityDaoConfig, this);

        registerDao(CustomerEntity.class, customerEntityDao);
    }
    
    public void clear() {
        customerEntityDaoConfig.getIdentityScope().clear();
    }

    public CustomerEntityDao getCustomerEntityDao() {
        return customerEntityDao;
    }

}
